---
postgres: &postgres
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: db
  username: exercism
  password: apples

test:
  <<: *postgres
  database: db_test

development:
  <<: *postgres
  database: db_development

production:
  <<: *postgres
  database: exercism_production
